export enum screens {
    SIGN_IN = "SIGN_IN",
    REGISTER = "REGISTER",
    DASHBOARD = "DASHBOARD",
    MY_READING_LISTS = "MY_READING_LISTS",
    BOOK_DETAILS = "BOOK_DETAILS",
    LIST_DETAILS = "LIST_DETAILS",
    GENRE_DETAILS = "GENRE_DETAILS",
    SEARCH_DETAILS = "SEARCH_DETAILS",
    USER_INFO = "USER_INFO",
    PROFILE = "PROFILE",
    EDIT_PROFILE = "EDIT_PROFILE",

}